services:
    twig.extension.adn_summernote:
        class: ADN\SummernoteBundle\Twig\Extension\ADNSummernoteExtension
        public: false
        arguments:
            - %adn_summernote%
            - @twig
        tags:
            - { name: twig.extension }
